Controllers/AppointmentsController.cs
using DoctorAppointment.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DoctorAppointment.Controllers
{
	public class AppointmentsController : Controller
	{
		ApplicationDbContext _context;
		
		public AppointmentsController(ApplicationDbContext context)
		{
			_context = context;
			
		}

		[HttpGet]
		
        public IActionResult GetIndexView(string? search)
        {
            ViewBag.Search = search;

            if (string.IsNullOrEmpty(search) == true)
            {
                return View("Index", _context.Patients.ToList());

            }
            else
            {
                return View("Index", _context.Patients.Where(d => d.FirstName.Contains(search) ||
                                                        d.LastName.Contains(search)).ToList());
            }

        }
    }
}

Controllers/DoctorsController.cs
using DoctorAppointment.Data;
using DoctorAppointment.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DoctorAppointment.Controllers
{
	public class DoctorsController : Controller
	{
		ApplicationDbContext _context;
		IWebHostEnvironment _webHostEnvironment;
		public DoctorsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
		{
			_context = context;
			_webHostEnvironment = webHostEnvironment;
		}

		[HttpGet]
		public IActionResult GetIndexView(string? search)
		{
			ViewBag.Search = search;

			if (string.IsNullOrEmpty(search) == true)
			{
				return View("Index", _context.Doctors.ToList());

			}
			else
			{
				return View("Index", _context.Doctors.Where(d => d.FirstName.Contains(search) ||
														d.Specialization.Contains(search)).ToList());
			}

		}




		[HttpGet]
		public IActionResult GetDetailsView(int id)
		{

			Doctor doc = _context.Doctors.Include(d => d.Patients).FirstOrDefault(d => d.DoctorId == id);

			ViewBag.CurrentDept = doc;

			if (doc == null)
			{
				return NotFound();
			}
			else
			{
				return View("Details", doc);
			}

		}

		[HttpGet]
		public IActionResult GetCreateView()
		{
			ViewBag.AllDoctors = _context.Patients.ToList();
			return View("Create");
		}

		[HttpPost]
		public IActionResult AddNew(Doctor doc, IFormFile? imageFormFile)
		{
			//(GUID)->Globally Unique Identifier
			if (imageFormFile != null)
			{
				string imgExtension = Path.GetExtension(imageFormFile.FileName);
				Guid imgGuid = Guid.NewGuid();
				string imgName = imgGuid + imgExtension;
				string imgPath = "\\images\\" + imgName;
				doc.ImagePath = imgPath;
				string imgFullPath = _webHostEnvironment.WebRootPath + imgPath;
				FileStream imgFileStream = new FileStream(imgFullPath, FileMode.Create);
				imageFormFile.CopyTo(imgFileStream);
				imgFileStream.Dispose();
			}
			else
			{
				doc.ImagePath = "\\images\\No_Image.png";
			}

			if (ModelState.IsValid == true)
			{
				_context.Doctors.Add(doc);
				_context.SaveChanges();
				return RedirectToAction("GetIndexView");
			}
			else
			{
				return View("Create", doc); //(RedirectToAction)->Doesn't save data in case error

			}

		}

		[HttpGet]

		public IActionResult GetEditView(int id)
		{

			Doctor doc = _context.Doctors.FirstOrDefault(d => d.DoctorId == id);
			if (doc == null)
			{
				return NotFound();
			}
			else
			{
				return View("Edit", doc);
			}

		}


		[HttpPost]
		public IActionResult EditCurrent(Doctor doctor, IFormFile? imageFormFile)
		{
			if (ModelState.IsValid == true)
			{
				if (imageFormFile != null)
				{
					if (doctor.ImagePath != "\\images\\No_Image.png")
					{
						string oldImgFullPath = _webHostEnvironment.WebRootPath + doctor.ImagePath;
						System.IO.File.Delete(oldImgFullPath);
					}
					string imgExtension = Path.GetExtension(imageFormFile.FileName);
					Guid imgGuid = Guid.NewGuid();
					string imgName = imgGuid + imgExtension;
					string imgPath = "\\images\\" + imgName;
					doctor.ImagePath = imgPath;
					string imgFullPath = _webHostEnvironment.WebRootPath + imgPath;
					FileStream imgFileStream = new FileStream(imgFullPath, FileMode.Create);
					imageFormFile.CopyTo(imgFileStream);
					imgFileStream.Dispose();
				}

				_context.Doctors.Update(doctor);
				_context.SaveChanges();
				return RedirectToAction("GetIndexView");
			}
			else
			{
				return View("Edit", doctor); //(RedirectToAction)->Doesn't save data in case error

			}

		}

		[HttpGet]
		public IActionResult GetDeleteView(int id)
		{
			
			Doctor doc = _context.Doctors.Include(d => d.Patients).FirstOrDefault(d => d.DoctorId == id);
			ViewBag.CurrentDept = doc;
			if (doc == null)
			{
				return NotFound();
			}
			else
			{
				return View("Delete", doc);
			}
		}


		[HttpPost]
		public IActionResult DeleteCurrent(int DoctorId)
		{
			Doctor doc = _context.Doctors.Find(DoctorId);
			if (doc != null && doc.ImagePath != "\\images\\No_Image.png")
			{
				string imgFullPath = _webHostEnvironment.WebRootPath + doc.ImagePath;
				System.IO.File.Delete(imgFullPath);
			}
			_context.Doctors.Remove(doc);
			_context.SaveChanges();

			return RedirectToAction("GetIndexView");
		}
	}
}

Controllers/PatientsController.cs
using DoctorAppointment.Data;
using DoctorAppointment.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DoctorAppointment.Controllers
{
	public class PatientsController : Controller
	{
		ApplicationDbContext _context;
		IWebHostEnvironment _webHostEnvironment;
		public PatientsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
		{
			_context = context;
			_webHostEnvironment = webHostEnvironment;
		}

		[HttpGet]
		public IActionResult GetIndexView(string? search)
		{
			ViewBag.Search = search;

			if (string.IsNullOrEmpty(search) == true)
			{
				return View("Index", _context.Patients.ToList());

			}
			else
			{
				return View("Index", _context.Patients.Where(d => d.FirstName.Contains(search) ||
														d.Address.Contains(search)).ToList());
			}

		}




		[HttpGet]
		public IActionResult GetDetailsView(int id)
		{

			Patient pat = _context.Patients.Include(d => d.Doctors).FirstOrDefault(d => d.PatientId == id);

			ViewBag.CurrentDept = pat;

			if (pat == null)
			{
				return NotFound();
			}
			else
			{
				return View("Details", pat);
			}

		}

		[HttpGet]
		public IActionResult GetCreateView()
		{
			ViewBag.AllDoctors = _context.Doctors.ToList();
			return View("Create");
		}

		[HttpPost]
		public IActionResult AddNew(Patient pat, IFormFile? imageFormFile)
		{
			//(GUID)->Globally Unique Identifier
			if (imageFormFile != null)
			{
				string imgExtension = Path.GetExtension(imageFormFile.FileName);
				Guid imgGuid = Guid.NewGuid();
				string imgName = imgGuid + imgExtension;
				string imgPath = "\\images\\" + imgName;
				pat.ImagePath = imgPath;
				string imgFullPath = _webHostEnvironment.WebRootPath + imgPath;
				FileStream imgFileStream = new FileStream(imgFullPath, FileMode.Create);
				imageFormFile.CopyTo(imgFileStream);
				imgFileStream.Dispose();
			}
			else
			{
				pat.ImagePath = "\\images\\No_Image.png";
			}

			if (ModelState.IsValid == true)
			{
				_context.Patients.Add(pat);
				_context.SaveChanges();
				return RedirectToAction("GetIndexView");
			}
			else
			{
                ViewBag.AllDoctors = _context.Doctors.ToList();
                return View("Create", pat); //(RedirectToAction)->Doesn't save data in case error

			}

		}

		[HttpGet]
		public IActionResult GetEditView(int id)
		{

			Patient patient= _context.Patients.FirstOrDefault(d => d.PatientId == id);
			if (patient == null)
			{
				return NotFound();
			}
			else
			{
				ViewBag.AllDoctors = _context.Doctors.ToList();
				return View("Edit", patient);
			}

		}



		[HttpPost]
		public IActionResult EditCurrent(Patient patient, IFormFile? imageFormFile)
		{
			if (ModelState.IsValid == true)
			{
				if (imageFormFile != null)
				{
					if (patient.ImagePath != "\\images\\No_Image.png")
					{
						string oldImgFullPath = _webHostEnvironment.WebRootPath + patient.ImagePath;
						System.IO.File.Delete(oldImgFullPath);
					}
					string imgExtension = Path.GetExtension(imageFormFile.FileName);
					Guid imgGuid = Guid.NewGuid();
					string imgName = imgGuid + imgExtension;
					string imgPath = "\\images\\" + imgName;
					patient.ImagePath = imgPath;
					string imgFullPath = _webHostEnvironment.WebRootPath + imgPath;
					FileStream imgFileStream = new FileStream(imgFullPath, FileMode.Create);
					imageFormFile.CopyTo(imgFileStream);
					imgFileStream.Dispose();
				}

				_context.Patients.Update(patient);
				_context.SaveChanges();
				return RedirectToAction("GetIndexView");
			}
			else
			{
				ViewBag.AllDoctors = _context.Doctors.ToList();
				return View("Edit", patient); //(RedirectToAction)->Doesn't save data in case error

			}

		}

		[HttpGet]
		public IActionResult GetDeleteView(int id)
		{

			Patient patient = _context.Patients.Include(d => d.Doctors).FirstOrDefault(d => d.PatientId == id);
			ViewBag.CurrentDept = patient;
			if (patient == null)
			{
				return NotFound();
			}
			else
			{
				return View("Delete", patient);
			}
		}


		[HttpPost]
		public IActionResult DeleteCurrent(int PatientId)
		{
			Patient patient = _context.Patients.Find(PatientId);
			if (patient != null && patient.ImagePath != "\\images\\No_Image.png")
			{
				string imgFullPath = _webHostEnvironment.WebRootPath + patient.ImagePath;
				System.IO.File.Delete(imgFullPath);
			}
			_context.Patients.Remove(patient);
			_context.SaveChanges();

			return RedirectToAction("GetIndexView");
		}
	}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DoctorAppointment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DoctorAppointment.styles.css" asp-append-version="true" />
    <link href="~/css/cerulean.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DoctorAppointment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctors" asp-action="GetIndexView">Doctor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patients" asp-action="GetIndexView">Patient</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="GetIndexView">Appointments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DoctorAppointment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>